export {Catalog} from "./Catalog"
export {Collection} from "./Collection"
export {Home} from "./Home"
export {Kids} from "./Kids"
export {MovieDetail} from "./MovieDetail"
export {MyMovie} from "./MyMovie"
export {Person} from "./Person"
export {Profile} from "./Profile"
export {Register} from "./Register"
export {Search}from "./Search"
export {Subscriptions} from "./Subscriptions"